name: Aggiorna elenco file in Blog

on:
  push:
    paths:
      - 'Blog/**'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Esegui lo script per aggiornare index.md
        run: python generate_index.py

      - name: Commit & Push se ci sono modifiche
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Blog/index.md
          git commit -m "Aggiornato automaticamente index.md 📂" || echo "Nessuna modifica da committare"
          git push
